export const AppConfig = {
  site_name: 'hewig.dev',
  title: 'Tao\'s Devlog',
  description:
    'Tao Xu (hewig) — Tokyo-based software engineer and blockchain developer, former founding engineer at Trust Wallet. Open-source Rust tools, macOS apps, and crypto wallet infrastructure.',
  // Real / display name — used for <meta name="author">, Person JSON-LD, and meta copy.
  name: 'Tao Xu',
  // GitHub handle — kept as Person.alternateName and the legacy author byline.
  author: 'hewigovens',
  jobTitle: 'Software Engineer & Technical Consultant',
  url: 'https://hewig.dev',
  // Default 1200x630 social-share card (generated by scripts/gen-og.mjs).
  og_image: '/og-image.png',
  locale_region: 'en-us',
  locale: 'en',
  social: {
    github: 'https://github.com/hewigovens',
    telegram: 'https://t.me/hewig',
    line: 'https://line.me/ti/p/~hewigovens',
    farcaster: 'https://warpcast.com/h1',
    twitter: 'https://x.com/hewigovens',
    youtube: 'https://www.youtube.com/hewigovens',
    email: 'hi@hewig.dev',
    newsletter: 'https://quail.ink/hewig',
    sponsor: 'https://github.com/sponsors/hewigovens',
  },
};
